core/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path("", views.index, name = "index"),
    path("register/", views.register, name = "register"),
] 

app_name = "core"

notes/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path("<str:username>/", views.notes_index, name = "notes_index"),
    path("<str:username>/<int:pk>/", views.note_page, name = "note_page"),
    path("<str:username>/<int:pk>/quiz/", views.quiz_page, name = "quiz_page"),
    path("<str:username>/<int:pk>/quiz/result/<int:qs>", views.results_page, name = "results_page"),
] 

app_name = "notes"

notest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', 'core'), name = 'core'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('notes/', include('notes.urls', 'notes'), name = 'notes'),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))

]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.urls import reverse
import re

def index(request):
    context = {
        "username": request.user.get_username()
    }
    return render(request, "core/index.html", context)

def register(request):
    context = None

    if request.method == "POST":
        form = request.POST
        username = form['username']
        email = form['email']
        password_1 = form['password_1']
        password_2 = form['password_2']
        first_name = form["fname"]
        last_name = form['lname']
        error = None

        if not username:
            error = 'Username is required.'
        elif not email:
            error = 'Email is required'
        elif not password_1:
            error = 'Password is required.'
        elif not password_2:
            error = 'Password is required.'
        elif password_1 != password_2:
            error = "Passwords don\'t match"
        elif re.match('^([a-z]*|[A-Z]*|[0-9]*|.{0,7})$', password_1):
            error = "Passwords must have at least 8 characters, an uppercase letter, and a number"
        elif not email:
            error = "Email is required."
        elif len(User.objects.filter(username=username)) > 0:
            error = f'User {username} is already registered.'.format(username)

        if error is None:
            User.objects.create_user(
                username=username,
                email=email,
                password=password_1,
                first_name=first_name,
                last_name=last_name
                )

            return redirect("login")

        context = {
        'error' : error
        }

        print(error)

    return render(request, "registration/register.html", context)

core/templates/core/index.html
{% extends "base.html" %}
{% block content %}
	<!--Name-->
	<div class>
		<div class="container" style="color: black; background-size: cover;">
			<div class = "col-lg-12" align="center">
				<h1 class="page-name"><span style = "color: #E1F4CB"> N O T E </span> S T 
				</h1>
				{% if user.is_authenticated %}
				<h1 class = "col-lg-12 page-name" style = "font-size: 2rem; margin-bottom: 40px" align="center"> Welcome <span style = "color: #E1F4CB">{{user.first_name}} </span> </h1>
				{% else %}
				<h1 class = "col-lg-12 page-name" style = "font-size: 2rem; margin-bottom: 40px" align="center"> Welcome <span style = "color: #E1F4CB"> </span> </h1>
				{% endif %}
				<div>
					{% if user.is_authenticated %}
					<a class="ghost-button" href="{% url 'notes:notes_index' username=user.get_username %}">Notebooks</a>
					<a class="ghost-button" href="#quizzes">Quizzes</a>
					{% else %}
					<a class="ghost-button" href='{% url "login" %}'>Login</a>

					{% endif %}

				</div>
			</div>
		</div>
	


{% endblock content %}

core/templates/core/main.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	{% if user.is_authenticated %}
	<h1> Welcome {{user.get_username}}</h1>
	{% endif %}
	<a href='{% url "login" %}'> Login </a>
	<br>
	<a href='{% url "core:register" %}'> Register </a>
</body>
</html>