core/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path("", views.index, name = "index"),
    path("register/", views.register, name = "register"),
] 

app_name = "core"

notes/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path("<str:username>/", views.notes_index, name = "notes_index"),
    path("<str:username>/<int:pk>/", views.note_page, name = "note_page"),
    path("<str:username>/<int:pk>/quiz/", views.quiz_page, name = "quiz_page"),
    path("<str:username>/<int:pk>/quiz/result/<int:qs>", views.results_page, name = "results_page"),
] 

app_name = "notes"

notest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', 'core'), name = 'core'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('notes/', include('notes.urls', 'notes'), name = 'notes'),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))

]

notes/models.py
from django.db import models
from django.contrib.auth.models import *

# Create your models here.

class Note(models.Model):
	title = models.CharField(max_length = 255)
	created_on = models.DateTimeField(auto_now_add=True)
	user = models.ForeignKey(User, unique=False, on_delete=models.CASCADE)
	tags = models.ManyToManyField('tag', related_name='notes')

	def __str__(self):
		return self.title

class Tag(models.Model):
	name = models.CharField(max_length=35)
	def __str__(self):
		return self.name

class Section(models.Model):
	title = models.CharField(max_length = 255)
	note = models.ForeignKey(Note, on_delete=models.CASCADE)

	def __str__(self):
		return self.title

class Term(models.Model):
	name = models.CharField(max_length = 255)
	section = models.ForeignKey(Section, on_delete=models.CASCADE)

	def __str__(self):
		return self.name

class Example(models.Model):
	text = models.CharField(max_length = 255)
	term = models.ForeignKey(Term, on_delete=models.CASCADE)

	def __str__(self):
		return self.text

class Definition(models.Model):
	text = models.CharField(max_length = 255)
	term = models.ForeignKey(Term, on_delete=models.CASCADE)

	def __str__(self):
		return self.text


class Question(models.Model):
	question = models.CharField(max_length = 255)
	answer = models.CharField(max_length = 255)
	term = models.ForeignKey(Term, on_delete=models.CASCADE)

	def __str__(self):
		return f"{self.question}: {self.answer}"


"""
class Result(models.Model):
	correct = models.IntegerField()
	total = models.IntegerField()
	note = models.ForeignKey(Note, on_delete=models.CASCADE)

	def __str__(self):
		return f"{self.correct}/{self.correct}"
"""

notes/views.py
from django.shortcuts import render, redirect
from django.core import serializers
from .models import *
from .serializers import *
from django.contrib.auth import *
from rest_framework import viewsets
from rest_framework import permissions
import json
import random

# Create your views here.

def quiz_page(request, username, pk):
    context = None
    if request.method == "POST":
     
        form = request.POST
        questions = {"questions": []}
        for i in range(int(form.get("qs"))):
            t = random.choice(Term.objects.filter(section__note__id = pk))

            possible_qs = []
            for e in Example.objects.filter(term = t):
                possible_qs.append(e.text)
            for d in Definition.objects.filter(term = t):
                possible_qs.append(d.text )
            for q in Question.objects.filter(term = t):
                possible_qs.append((q.question, q.answer))
            if len(possible_qs) == 0:
                continue
                
            q = random.choice(possible_qs)
            print(q)
            if type(q) == "Tuple":
                ques = q[0]
                a = q[1]
                w_as = [random.choice(Question.objects.filter(term = t).exclude(answer = a)).answer for j in range(3)]
            elif q:
                ques = f"{q}"
                a = t.name
                poss_w_as = []
                for b in Term.objects.exclude(name = t.name):
                    poss_w_as.append(b.name)
                w_as = {random.choice(poss_w_as) for _ in range(3)}
            else:
                continue
            print(a)
            answers = [(a, True)]
            for w_a in w_as:
                answers.append((w_a, False))
            random.shuffle(answers)
            questions['questions'].append({"question": ques, "answer" : answers})
            print(questions)
            print(answers)

        context = {
                "questions" : questions,
                "pk": pk,
                "qs" : int(form["qs"])
        }
              

        return render(request, "notes/quiz_page.html", context)

     
def results_page(request, username, pk, qs):
    if request.method == "POST":
        form = request.POST
        print(form)
        correct = 0

        for i in range(1, int(qs) + 1):
            if form.get(f"answer-{i}") == "True":
                correct += 1


        context = {
            "correct": correct,
            "qs" : qs,
            "pk" : pk
        }

        #result = Result(correct = correct, total = qs, note = Note.objects.get(pk = pk))
        #result.save()

        return render(request, "notes/results_page.html", context)



def notes_index(request, username):
    if request.method == "POST":
        form = request.POST
        n = Note(title = form.get("title"), user = request.user)
        n.save()

    context = None
    user = request.user

    if user.is_authenticated and user.get_username() == username:
        notes = Note.objects.filter(user=user)

        context = {
            "notes" : notes
        }

        return render(request, "notes/notes_index.html", context)

    else:
        return redirect("login")

def note_page(request, username, pk):
    if request.method == "POST":
        form = request.POST

        text = form.get("text")
        model = form.get("model")
        parent = form.get("parent")
        n = Note.objects.get(pk = pk)

        if model == "Section":
            s = Section(title = text, note = n)
            s.save()
        if model == "Term":
            t = Term(name = text, section = Section.objects.filter(title__icontains = parent).first())
            t.save()
        if model == "Definition":
            d = Definition(text = text, term = Term.objects.filter(name__icontains = parent).first())
            d.save()
        if model == "Example":
            e = Example(text = text, term = Term.objects.filter(name__icontains = parent).first())
            e.save()
        

    context = None
    user = request.user
    if user.is_authenticated and user.get_username() == username:
        if pk in [note.id for note in Note.objects.filter(user=user)]:
            n = Note.objects.get(pk = pk)
            # print(Result.objects.filter(note = n))

            note = {}
            note["sections"] = []
            for i, s in enumerate(Section.objects.filter(note__id = pk)):
                note["sections"].append({})
                note["sections"][i]["section_title"] = s.title
                note["sections"][i]["terms"] = []
                for j, t in enumerate(Term.objects.filter(section  = s)):
                    note["sections"][i]["terms"].append({})
                    note["sections"][i]["terms"][j]["term_name"] = t.name

                    
                    note["sections"][i]["terms"][j]["definitions"] = [d.text for d in Definition.objects.filter(term = t)]

                
                    note["sections"][i]["terms"][j]["examples"] = [e.text for e in Example.objects.filter(term = t)]


                    note["sections"][i]["terms"][j]["questions"] = [q.text for q in Question.objects.filter(term = t)]
            

            context = {
                "notes": note,
                "note": n,
                #"results": results
            }



            return render(request, "notes/note_page.html", context)

        else:
            return redirect("notes:notes_index", user.get_username())

    else:
        return redirect("login")



        

notes/templates/notes/note_page.html
{% extends 'base.html' %}
{% block content %}
	<div class="container" style="background-size: cover;">
			<div class = "col-lg-12" align="center">
				<h1 class="page-header mb-5"><span style = "color: #E1F4CB"> N O T E </span> S
				</h1>
				
			</div>
			<div class = "col-lg-12" align="center">
				<h2 class="page-subheader mb-5">{{note.title}}
				</h2>
			</div>

			<!---
		<div class = "row">
			{% if results %}
			<h2 class = "col-12">
				Previous Results:
			</h2>
			<div class="col-12">
			{% for result in results %}
						<p>{{result}}</p>
			{% endfor %}
			</div>
			{% endif %}
		</div>
		!--->
	<div class="row">
		<div class = "col-md-10 mb-3 list-group">
		{% for section in notes.sections %}
			<div class="list-group-item section nested-sortables" style="background-color: #717568"> <p class="notes-section-title">{{section.section_title}} </p>

			{% for term in section.terms %}
				<div class="list-group-item term nested-sortables" style="background-color: #BACBA9"><p class="notes-term-name" style = "color: white"> {{term.term_name}} </p>
					{% for def in term.definitions %}
						<div class="list-group-item definition" style="background-color: #E1F4CB"><p class="notes-def">Definition: {{def}} </p>
						</div>
					{% endfor %}
					{% for ex in term.examples %}
						<div class="list-group-item definition" style="background-color: #E1F4CB"><p class="notes-def">Ex: {{ex}} </p>
						</div>
					{% for q in term.questions %}
					<div class="list-group-item definition" style="background-color: #E1F4CB"><p class="notes-def"> {{ex}} </p>
						</div>
					{% endfor %}
					{% endfor %}
				</div>
			{% endfor %}
			</div>
		

		{% endfor %}
		</div>
		<div class = "col-md-2 mb-3" >
			<h2 class = "notes-section-title">QUIZ</h2>
			<form method="post" action="{% url 'notes:quiz_page' user.get_username note.pk %}">
		    {% csrf_token %}
		     
			<p class="question">Number of Questions</p>
			<input class="text-box" type="text" id="qs" name="qs"><br><br>
		    <input class="button" type="submit" value="Quiz" />
		    <input type="hidden" name="next" value=""> 
		  </form>
		</div>

	</div>

	<br>
	<div class = "row">
		<h1 class="form mb-3" style="font-weight: bold; font-size: 2rem;">Create A Card</h1>
	</div>
	<form method = "post" action="{% url 'notes:note_page' user.get_username note.pk %}">
		  	{% csrf_token %}
		<div class="row">

		  <div class="col-md-2 mb-5">
		  	
		  	<br>
		  	<div class = "row">

		  	<input type="radio" id="section" name="model" value="Section"><br><br>
		  		<label class="notes-add" for="section">Section</label>
		  	</div>
		  	<div class = "row">
				  <input type="radio" id="term" name="model" value="Term"><br><br>
				<label class="notes-add" for="term">Term</label>
				</div>
			<div class = "row">
				  <input type="radio" id="definition" name="model" value="Definition"><br><br>
				<label class="notes-add" for="definition">Definition</label>
				</div>
			<div class = "row">
				   <input type="radio" id="example" name="model" value="Example"><br><br>
				   <label class="notes-add" for="example">Example</label>
				   </div>
			</div>
				 
				 
		  <div class="col-md-4 mb-5">
		  		<p class = "notes-add-2">Parent</p>
			  	<input class="notes-text-box" type="text" id="parent" name="parent"><br><br>
			  	<p class = "notes-add-2">Text</p>		 	 
			  	<input class="notes-text-box" type="text" id="text" name="text"><br><br>
			  <input class="button" type="submit" value="Submit" />
		    <input type="hidden" name="next" value="">
		  </div>
		 </div>
		</form>

	 </div>
	
	<script src="https://cdn.jsdelivr.net/npm/sortablejs@latest/Sortable.min.js"></script>

	<script>
		var nestedSortables = [].slice.call(document.querySelectorAll(".nested-sortables"))

		for(var i = 0; i < nestedSortables.length; i++){
			new Sortable(nestedSortables[i], {
				group: "nested",
				animation: 150,
				ghostClass: "text-info",
				fallbackOnBody: true,
				swapThreshold: 1,
				invertSwap: true,
			})
		}
	</script>

{% endblock content %}

	
	

notes/templates/notes/notes_index.html
{% extends "base.html"%}
{% block content %}

	<!--Name-->
	<div class>
		<div class="container" style="background-size: cover;">
			<div class = "col-lg-12" align="center">
				<h1 class="page-header"><span style = "color: #E1F4CB"> N O T E </span> B O O K S
				</h1>
			</div>
			<div class="col-md-12 mb-5" align="center">
				{% for note in notes %}
				<a class="ghost-button-notebook my-2" href="{% url 'notes:note_page' user.get_username note.pk %}">{{note.title}}</a>
				{% endfor %}
			</div>
			<div class="col-md-12 my-5" align="center">

				<form method = "post" action = "{% url 'notes:notes_index' user.get_username %}">
				{% csrf_token %}
				<label style="display: block; color: white" class="form" for="title">Create a New Notebook</label>
				<input type="text" id="title" name="title"><br><br>
				<input class="ghost-button" type="submit" value="Submit" style="background-color: #717568">
				</form>
			</div>
		</div>
	</div>
{% endblock content %}

notes/templates/notes/quiz_page.html
{% extends 'base.html' %}
{% block content %}

	<div class="container" style="background-size: cover;">
			<div class = "col-lg-12" align="center">
				<h1 class="page-header">Q U I Z
				</h1>
			</div>

	<form method="POST" action = "{% url 'notes:results_page' user.get_username pk qs %}">
		{% csrf_token %}
	{% for question in questions.questions %}
		<p class="question" style="font-weight: bold; font-size: 2rem;">{{question.question}}</p>
		
		{% for answer in question.answer %}
		<div class = "row">
			<input id = "answer" type="radio" name="answer-{{forloop.parentloop.counter}}" value="{{answer.1}}"><p class="question" style="display: inline-block; font-size: 1.5rem;"></p>
			<label class = "notes-add" for = "answer">{{answer.0}}</label>
		</div>
        {% endfor %}
	{% endfor %}
	<div class="row my-5">
		<input class="button" type="submit" value="Submit">
	</div>
     </form>
   </div>

<script type="text/javascript">
	var ul = document.querySelector('ul');
	for (var i = ul.children.length; i >= 0; i--) {
    	ul.appendChild(ul.children[Math.random() * i | 0]);
	}	

</script>

{% endblock content %}

notes/templates/notes/result_page.html
{% extends 'base.html' %}
{% block content %}
	<p> You got {{correct}} out of {{qs}} questions right!</p>
	<a href="{% url 'notes:note_page' user.get_username pk %}"> Return to note </a>
{% endblock content%}

notes/templates/notes/results_page.html
{% extends 'base.html' %}
{% block content %}

<div class="container" style="background-size: cover;">
	<div class = "col-lg-12" align="center">
			<h1 class="page-header">R E S U L T S
			</h1>
	</div>

	<div class = "col-lg-12" align="center">
		<p class="question" style="font-weight: bold; font-size: 2rem;"> You got {{correct}} out of {{qs}} questions right!</p>
	</div>
	<div class = "col-lg-12" align="center">
		<a class="button" style="color: #717568" href="{% url 'notes:note_page' user.get_username pk %}"> Return to note </a>
	</div>
</div>
{% endblock content%}