core/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path("", views.index, name = "index"),
    path("register/", views.register, name = "register"),
] 

app_name = "core"

notest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', 'core'), name = 'core'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('notes/', include('notes.urls', 'notes'), name = 'notes'),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))

]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>notest</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>
<body style="background-color: #717568">

	<!-- Nav Bar-->
	<nav class="navbar navbar-fixed fixed-top navbar-expand-md">
	    <div class="container">
	        <a class="navbar-brand" href="/">
				<img class="nav-img" src="{% static 'notestlogo.png' %}" alt="Notest Logo">
			</a>
	         <button class="navbar-dark navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    			<span class="navbar-toggler-icon"></span>
  			</button>
	        <div class="collapse navbar-collapse" id="navbarNav">
	            <ul class="navbar-nav ml-auto">

	                <li class="nav-item">
					<a class="nav-link scroll-link" href="{% url 'core:index' %}">Home</a>
				</li>
				
				<li class="nav-item">
					<a class="nav-link scroll-link" href='{% url "login" %}'>Login</a>
				</li>
				<li class="nav-item">
					<a class="nav-link scroll-link" href="{% url 'core:register' %}">Register</a>
				</li>
	                
	            </ul>
	        </div>
	    </div>
	</nav>

	<!--Editable-->
	{% block content %}
	{% endblock content %}
	
	
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/sortablejs@latest/Sortable.min.js"></script>
</body>
</html>